### ISSUE TITLE
Error on gridsome deploy

### ISSUE THREAD

**Issue by annettaws** [tanc/gridsome-cockpit-source#3]
Hi i'm trying to use your plugin to get data from my cockpit cms but on gridsome deploy i got this error:

Initializing plugins...
TypeError: Expected "slug" to be a string
    at C:\Users\annad\Desktop\my-gridsome-site\node_modules\path-to-regexp\index.js:194:13
    at makePath (C:\Users\annad\Desktop\my-gridsome-site\node_modules\gridsome\lib\plugins\TemplatesPlugin.js:77:10)
    at C:\Users\annad\Desktop\my-gridsome-site\node_modules\gridsome\lib\plugins\TemplatesPlugin.js:205:24
    at SyncBailWaterfallHook.eval [as call] (eval at create (C:\Users\annad\Desktop\my-gridsome-site\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:19:16)
    at Collection.addNode (C:\Users\annad\Desktop\my-gridsome-site\node_modules\gridsome\lib\store\Collection.js:72:50)
    at C:\Users\annad\Desktop\my-gridsome-site\node_modules\@tanc00\gridsome-source-cockpit\index.js:117:20
    at Array.forEach (<anonymous>)
    at CockpitSource.getEntries (C:\Users\annad\Desktop\my-gridsome-site\node_modules\@tanc00\gridsome-source-cockpit\index.js:72:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\annad\Desktop\my-gridsome-site\node_modules\@tanc00\gridsome-source-cockpit\index.js:30:7
    at async Plugins.run (C:\Users\annad\Desktop\my-gridsome-site\node_modules\gridsome\lib\app\Plugins.js:141:11)

on gridsome.config.js the settings of plugin are:
{
            use: '@tanc00/gridsome-source-cockpit',
            options: {
              accessToken: process.env.ACCESSTOKEN,
              host: process.env.APIHOST,
            }
          },

**Comment by tanc** [comment]
I’m afraid things have moved on in Gridsome since I wrote this plugin so things will probably be broken. But if you find a solution please post here or issue a merge request

**Comment by tanc** [comment]
Its occurred to me that maybe you're using `:slug` in a route definition as per the example in the README.md but without a corresponding field called `slug` in cockpit?

As per the example `gridsome.config.js`:

```
routes: {
          page: '/:slug',
}
```

If I remember correctly (it's been a while since I used this plugin) you'd need to have a field in Cockpit named `slug` with a String value on that collection (called `page`).

**Comment by annettaws** [comment]
I added slug field on my collections but i had the same error.
Anyway i found a solution to use it in gridsome.
I istalled a [graphql addons](https://github.com/agentejo/CockpitQL) on cockpit and with [@gridsome/source-graphql](https://gridsome.org/plugins/gridsome-source-graphql) i can get the data.
